{
 "title": "Advanced_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Incoming logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming audit logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, count() as audit_logs_count FROM \"vault\".\"auditlogs\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time ORDER BY time ASC LIMIT 5000"
    }
   ]
  },
  {
   "title": "Incoming operational logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, count() as operational_logs_count FROM \"vault\".\"operation\" WHERE ( time >= $__fromTime AND time <= $__toTime ) GROUP BY time ORDER BY time ASC LIMIT 5000"
    }
   ]
  },
  { "title": "Top consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Remote addresses with over 100 operations per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT time, remote_ip, count_operation\nFROM\n(\n  SELECT \n    timestamp as time, \n    log.request.remote_address as remote_ip, \n    count() as count_operation \n  FROM \"vault\".\"auditlogs\" \n  WHERE \n    ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' ) \n  GROUP BY time, remote_ip \n  ORDER BY time, count_operation ASC\n)\nWHERE count_operation > 100"
    }
   ]
  },
  {
   "title": "Namespaces with over 50 operations per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT time, namespace, count_operation\nFROM\n(\n  SELECT \n    timestamp as time, \n    log.request.namespace.id as namespace, \n    count() as count_operation \n  FROM \"vault\".\"auditlogs\" \n  WHERE \n    ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' ) \n  GROUP BY time, namespace \n  ORDER BY time, count_operation\n)\nWHERE count_operation > 50"
    }
   ]
  },
  {
   "title": "Paths with over 10 operations per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT time, path, count_operation\nFROM\n(\n  SELECT \n      timestamp as time, \n      log.request.path as path, \n      count() as count_operation \n  FROM \"vault\".\"auditlogs\" \n  WHERE \n    ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' ) \n  GROUP BY time, path \n  ORDER BY time, count_operation ASC\n)\nWHERE count_operation > 10"
    }
   ]
  },
  { "title": "Traffic per operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Vault total incoming traffic per operation group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, count() as total FROM \"vault\".\"auditlogs\" WHERE ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' ) GROUP BY time ORDER BY time ASC LIMIT 5000"
    },
    {
     "rawSql": "SELECT timestamp as time, count() as total_write FROM \"vault\".\"auditlogs\" WHERE ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' and (log.request.operation == 'create' or log.request.operation == 'update' or log.request.operation == 'delete')) GROUP BY time ORDER BY time ASC LIMIT 5000"
    },
    {
     "rawSql": "SELECT timestamp as time, count() as total_read FROM \"vault\".\"auditlogs\" WHERE ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' and (log.request.operation == 'read' or log.request.operation == 'list')) GROUP BY time ORDER BY time ASC LIMIT 5000"
    }
   ]
  },
  {
   "title": "Vault incoming traffic per operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT timestamp as time, log.request.operation as operation, count() as count_operation FROM \"vault\".\"auditlogs\" WHERE ( time >= $__fromTime AND time <= $__toTime and log.type == 'response' ) GROUP BY time, operation ORDER BY time ASC LIMIT 5000"
    }
   ]
  },
  { "title": "Log count per log level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "vault-n1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.level as level, \n  count(message.level) count_level\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n1.openlab.net') \nGROUP BY time, level \nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "vault-n2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.level as level, \n  count(message.level) count_level\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n2.openlab.net') \nGROUP BY time, level \nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "vault-n3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.level as level, \n  count(message.level) count_level\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n3.openlab.net') \nGROUP BY time, level \nORDER BY time ASC\n"
    }
   ]
  },
  { "title": "Logs count per vault modules", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "vault-n1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.module as module, \n  count(message.module) count_module\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n1.openlab.net' ) \nGROUP BY time, module \nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "vault-n2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.module as module, \n  count(message.module) count_module\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n2.openlab.net' ) \nGROUP BY time, module \nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "vault-n3",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  message.module as module, \n  count(message.module) count_module\nFROM \"vault\".\"operation\" \nWHERE \n  ( time >= $__fromTime AND time <= $__toTime and message.hostname == 'vault-n3.openlab.net' ) \nGROUP BY time, module \nORDER BY time ASC\n"
    }
   ]
  }
 ]
}