pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        ANSIBLE_CONFIG = "Lab-06/vault/ansible.cfg"
    }

    stages {
        stage('Install requirements') {
            steps{
                dir('Lab-06/vault') {
                    sh '''
                      ansible-galaxy install -r requirements/ansible-galaxy.yml
                      python -m ensurepip --upgrade
                      python -m pip install -r requirements/python.txt
                    '''
                }
            }
        }
        stage('Configure Telegraf') {
            steps{
                ansiblePlaybook playbook: 'Lab-06/metric/configure_telegraf.yml', colorized: true, credentialsId: 'aws-private-key'
            }
        }
        stage('Deploy Grafana dashboards') {
            steps{
                ansiblePlaybook playbook: 'Lab-06/metric/deploy_dashboards.yml', colorized: true
            }          
        }
    }
}