{
 "title": "Golden_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HAProxy - Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming requests per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"req_rate\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"main\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> drop(columns: [\"datacenter\", \"metric_type\", \"role\", \"host\", \"server\", \"proxy\", \"type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Incoming sessions per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"main\" or r[\"proxy\"] == \"vault\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"FRONTEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Number of active sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"scur\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"main\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"FRONTEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "HAProxy - Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rtime\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"vault\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"BACKEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average connect time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ctime\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"vault\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"BACKEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average queue time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"qtime\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"vault\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"BACKEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "HAProxy - Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "HTTP response errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response.4xx\" or r[\"_field\"] == \"http_response.5xx\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"main\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"FRONTEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ereq\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"main\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"FRONTEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "HAProxy - Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU saturation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> map(fn: (r) => ({r with _value: r._value * -1.0 + 100.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk saturation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current queued requests",
   "type": "timeseries",
   "description": "For the backend this reports the number queued without a server assigned.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"_field\"] == \"qcur\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"proxy\"] == \"vault\")\n  |> filter(fn: (r) => r[\"role\"] == \"haproxy\")\n  |> filter(fn: (r) => r[\"sv\"] == \"BACKEND\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Vault - Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Failure tolerance",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.autopilot.failure_tolerance\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"datacenter\", \"metric_type\", \"role\"])\n  |> drop(columns: [\"host\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Node health status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.autopilot.node.healthy\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"metric_type\", \"role\", \"host\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Seal status",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.core.unsealed\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"metric_type\", \"role\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lead/follower nodes",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.core.active\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"metric_type\", \"role\"])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Vault - Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Tokens creation rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.token.creation\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"auth_method\", \"creation_ttl\", \"mount_point\", \"namespace\", \"token_type\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of active tokens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.token.count\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"namespace\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Leases expiration rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.expire.num_leases\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"namespace\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Write load on storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.raft.apply\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"namespace\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Number of requests currently in progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.core.in_flight_requests\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Vault - Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Time required to complete request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.core.handle_login_request\" or r[\"_measurement\"] == \"vault.core.handle_request\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  \n  \n"
    }
   ]
  },
  {
   "title": "Time required to create a token",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vault.token.create\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mean\")\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"host\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  \n"
    }
   ]
  },
  { "title": "Vault - Saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "CPU saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_idle\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"metric_type\", \"cpu\"])\n  |> map(fn: (r) => ({r with _value: r._value * -1.0 + 100.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory saturation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"metric_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk saturation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"vault_infra\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"cluster\"] == \"test_cluster\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"datacenter\"] == \"us-east-1\")\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> drop(columns: [\"cluster\", \"datacenter\", \"role\", \"metric_type\", \"path\", \"mode\", \"fstype\", \"device\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}