pipeline {
    agent any
    environment {
        ANSIBLE_CONFIG = "Lab-03/vault/ansible.cfg"
    }
    parameters {
        string(name: 'VAULT_BENCHMARK_TOKEN', defaultValue: '', description: 'Vault token that will be used to run benchmark')
    }
    stages {
        stage('Generate Traffic') {
            steps{
                ansiblePlaybook playbook: 'Lab-03/traffic/generate_traffic.yml', colorized: true, extras: "-e vault_token=${params.SKIP_ALL_REVIEWS}"
            }
        }
    }
}