pipeline {
    agent any
    environment {
        ANSIBLE_CONFIG = "Lab-03/vault/ansible.cfg"
        DEPLOY_ROLE_ID = credentials('deploy-role-id')
        DEPLOY_SECRET_ID = credentials('deploy-secret-id')
    }
    stages {
        stage('Generate Traffic') {
            steps{
                ansiblePlaybook playbook: 'Lab-03/traffic/generate_traffic.yml', colorized: true
            }
        }
    }
}