pipeline {
  agent any

    stages {
        stage('Install requirements') {
            steps{
                dir('Lab-02/vault') {
                    sh '''
                      ansible-galaxy install -r requirements/ansible-galaxy.yml
                      python -m ensurepip --upgrade
                      python -m pip install -r requirements/python.txt
                    '''
                }
            }
        }
        stage('Configure Haproxy') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
            }
            steps{
                dir('Lab-02/vault') {
                    ansiblePlaybook(
                        playbook: 'haproxy_configure.yml',
                        credentialsId('aws-private-key')
                    )   
                }
            }
        }
        stage('Security Test') {
            steps{
                echo "Running Security tests"
            }          
        }
        stage('Build') {
            steps{
                echo "Building artifact"
            }          
        }
        stage('Push') {
            steps{
                echo "Storing artifact"
            }          
        }
        stage('Trigger CD') {
            environment {
                VAULT_TOKEN = credentials('autounseal-token')
            }
            steps{
                echo "${VAULT_TOKEN}"
            }          
        }
    }
}