pipeline {
  agent any

    stages {
        stage('Install requirements') {
            steps{
                dir('Lab-02/vault') {
                    sh '''
                      ansible-galaxy install -r requirements/ansible-galaxy.yml
                      pip3 install -r requirements/pyhton.txt
                    '''
                }
            }
        }
        stage('Configure Haproxy') {
            steps{
                dir('Lab-02/vault') {
                    sh '''
                        ansible-playbook haproxy_configure.yml
                    '''
                }
            }
        }
        stage('Security Test') {
            steps{
                echo "Running Security tests"
            }          
        }
        stage('Build') {
            steps{
                echo "Building artifact"
            }          
        }
        stage('Push') {
            steps{
                echo "Storing artifact"
            }          
        }
        stage('Trigger CD') {
            environment {
                VAULT_TOKEN = credentials('autounseal-token')
            }
            steps{
                echo "${VAULT_TOKEN}"
            }          
        }
    }
}